// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SisAlq.Api.Shared.Data;

#nullable disable

namespace SisAlq.Api.Migrations
{
    [DbContext(typeof(SisAlqDbContext))]
    [Migration("20260701025714_AddReciboConsumo")]
    partial class AddReciboConsumo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SisAlq.Api.Shared.Models.Catalogos.EstadoContrato", b =>
                {
                    b.Property<int>("IdEstadoContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstadoContrato"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdEstadoContrato");

                    b.ToTable("ESTADO_CONTRATO", (string)null);
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.Catalogos.EstadoInmueble", b =>
                {
                    b.Property<int>("IdEstadoInmueble")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstadoInmueble"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdEstadoInmueble");

                    b.ToTable("ESTADO_INMUEBLE", (string)null);
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.Catalogos.Moneda", b =>
                {
                    b.Property<int>("IdMoneda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMoneda"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("IdMoneda");

                    b.ToTable("MONEDA", (string)null);
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.Catalogos.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("IdRol");

                    b.ToTable("ROLES", (string)null);
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.Catalogos.Sector", b =>
                {
                    b.Property<int>("IdSector")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSector"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdSector");

                    b.ToTable("SECTOR_ZONA", (string)null);
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.Catalogos.TipoCliente", b =>
                {
                    b.Property<int>("IdTipoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoCliente"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdTipoCliente");

                    b.ToTable("TIPO_CLIENTE", (string)null);
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.Catalogos.TipoDocumento", b =>
                {
                    b.Property<int>("IdTDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTDocumento"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdTDocumento");

                    b.ToTable("TIPO_DOCUMENTO", (string)null);
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.Catalogos.TipoInmueble", b =>
                {
                    b.Property<int>("IdTipoInmueble")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoInmueble"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("IdTipoInmueble");

                    b.ToTable("TIPO_INMUEBLE", (string)null);
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.ConceptoConsumoServicio", b =>
                {
                    b.Property<int>("IdConceptoConsumo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConceptoConsumo"));

                    b.Property<string>("DescCorta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("Importe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TipoConcepto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UnidadMedida")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Vigente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("IdConceptoConsumo");

                    b.ToTable("CONCEPTO_CONSUMOSERVICIO", (string)null);
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.ContratoCab", b =>
                {
                    b.Property<int>("IdContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdContrato"));

                    b.Property<DateOnly>("FechaContrato")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateOnly>("FechaVcmto")
                        .HasColumnType("date");

                    b.Property<decimal>("Garantia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("IdEstadoContrato")
                        .HasColumnType("integer");

                    b.Property<int>("IdInquilino")
                        .HasColumnType("integer");

                    b.Property<int>("IdMoneda")
                        .HasColumnType("integer");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer");

                    b.Property<string>("NroContrato")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("NroMeses")
                        .HasColumnType("integer");

                    b.Property<string>("Representante")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("TipoNegocio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdContrato");

                    b.HasIndex("IdEstadoContrato");

                    b.HasIndex("IdInquilino");

                    b.HasIndex("IdMoneda");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("NroContrato")
                        .IsUnique();

                    b.ToTable("CONTRATO_CAB", (string)null);
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.ContratoDet", b =>
                {
                    b.Property<int>("IdContratoDet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdContratoDet"));

                    b.Property<int>("IdContrato")
                        .HasColumnType("integer");

                    b.Property<int>("IdInmueble")
                        .HasColumnType("integer");

                    b.Property<int>("NroMesPPago")
                        .HasColumnType("integer");

                    b.Property<int>("NroMeses")
                        .HasColumnType("integer");

                    b.Property<decimal>("RentaMensual")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdContratoDet");

                    b.HasIndex("IdContrato");

                    b.HasIndex("IdInmueble");

                    b.ToTable("CONTRATO_DET", (string)null);
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.Inmueble", b =>
                {
                    b.Property<int>("IdInmueble")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInmueble"));

                    b.Property<string>("CodigoInmueble")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DescripcionInmueble")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("IdEstadoInmueble")
                        .HasColumnType("integer");

                    b.Property<int>("IdMoneda")
                        .HasColumnType("integer");

                    b.Property<int>("IdSector")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoInmueble")
                        .HasColumnType("integer");

                    b.Property<char>("IncluyeServicios")
                        .HasMaxLength(1)
                        .HasColumnType("character(1)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("PisoInmueble")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal>("PrecioAlquiler")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdInmueble");

                    b.HasIndex("CodigoInmueble")
                        .IsUnique();

                    b.HasIndex("IdEstadoInmueble");

                    b.HasIndex("IdMoneda");

                    b.HasIndex("IdSector");

                    b.HasIndex("IdTipoInmueble");

                    b.ToTable("INMUEBLES", (string)null);
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.Inquilino", b =>
                {
                    b.Property<int>("IdInquilino")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInquilino"));

                    b.Property<string>("CelularTelefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("IdTDocumento")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoCliente")
                        .HasColumnType("integer");

                    b.Property<string>("NroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RsocialNApellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("boolean");

                    b.HasKey("IdInquilino");

                    b.HasIndex("IdTDocumento");

                    b.HasIndex("IdTipoCliente");

                    b.HasIndex("NroDocumento")
                        .IsUnique();

                    b.ToTable("CLIENTE", (string)null);
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.RingresoConsumoCab", b =>
                {
                    b.Property<int>("IdNroRecibo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNroRecibo"));

                    b.Property<DateTime>("FechaEmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GlosaConcepto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IdInmueble")
                        .HasColumnType("integer");

                    b.Property<int>("IdInquilino")
                        .HasColumnType("integer");

                    b.Property<int>("IdMoneda")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalRecibo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("IdNroRecibo");

                    b.HasIndex("IdInquilino");

                    b.HasIndex("IdMoneda");

                    b.HasIndex("IdInmueble", "GlosaConcepto")
                        .IsUnique();

                    b.ToTable("RINGRESO_CONSUMOCAB", (string)null);
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.RingresoConsumoDet", b =>
                {
                    b.Property<int>("IdNroRecibo")
                        .HasColumnType("integer");

                    b.Property<int>("Item")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FLecturaFinal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FLecturaInicial")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdConceptoConsumo")
                        .HasColumnType("integer");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("LecturaFinal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("LecturaInicial")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("IdNroRecibo", "Item");

                    b.HasIndex("IdConceptoConsumo");

                    b.ToTable("RINGRESO_CONSUMODET", (string)null);
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("CelularTelefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Correo")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<string>("NombreApellidos")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.ContratoCab", b =>
                {
                    b.HasOne("SisAlq.Api.Shared.Models.Catalogos.EstadoContrato", "EstadoContrato")
                        .WithMany()
                        .HasForeignKey("IdEstadoContrato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisAlq.Api.Shared.Models.Inquilino", "Inquilino")
                        .WithMany()
                        .HasForeignKey("IdInquilino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisAlq.Api.Shared.Models.Catalogos.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("IdMoneda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisAlq.Api.Shared.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoContrato");

                    b.Navigation("Inquilino");

                    b.Navigation("Moneda");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.ContratoDet", b =>
                {
                    b.HasOne("SisAlq.Api.Shared.Models.ContratoCab", "Contrato")
                        .WithMany("Detalle")
                        .HasForeignKey("IdContrato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisAlq.Api.Shared.Models.Inmueble", "Inmueble")
                        .WithMany()
                        .HasForeignKey("IdInmueble")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contrato");

                    b.Navigation("Inmueble");
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.Inmueble", b =>
                {
                    b.HasOne("SisAlq.Api.Shared.Models.Catalogos.EstadoInmueble", "EstadoInmueble")
                        .WithMany()
                        .HasForeignKey("IdEstadoInmueble")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisAlq.Api.Shared.Models.Catalogos.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("IdMoneda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisAlq.Api.Shared.Models.Catalogos.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("IdSector")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisAlq.Api.Shared.Models.Catalogos.TipoInmueble", "TipoInmueble")
                        .WithMany()
                        .HasForeignKey("IdTipoInmueble")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstadoInmueble");

                    b.Navigation("Moneda");

                    b.Navigation("Sector");

                    b.Navigation("TipoInmueble");
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.Inquilino", b =>
                {
                    b.HasOne("SisAlq.Api.Shared.Models.Catalogos.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("IdTDocumento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisAlq.Api.Shared.Models.Catalogos.TipoCliente", "TipoCliente")
                        .WithMany()
                        .HasForeignKey("IdTipoCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoCliente");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.RingresoConsumoCab", b =>
                {
                    b.HasOne("SisAlq.Api.Shared.Models.Inmueble", "Inmueble")
                        .WithMany()
                        .HasForeignKey("IdInmueble")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisAlq.Api.Shared.Models.Inquilino", "Inquilino")
                        .WithMany()
                        .HasForeignKey("IdInquilino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisAlq.Api.Shared.Models.Catalogos.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("IdMoneda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inmueble");

                    b.Navigation("Inquilino");

                    b.Navigation("Moneda");
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.RingresoConsumoDet", b =>
                {
                    b.HasOne("SisAlq.Api.Shared.Models.ConceptoConsumoServicio", "ConceptoConsumo")
                        .WithMany()
                        .HasForeignKey("IdConceptoConsumo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisAlq.Api.Shared.Models.RingresoConsumoCab", "Cabecera")
                        .WithMany("Detalle")
                        .HasForeignKey("IdNroRecibo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabecera");

                    b.Navigation("ConceptoConsumo");
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.Usuario", b =>
                {
                    b.HasOne("SisAlq.Api.Shared.Models.Catalogos.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.ContratoCab", b =>
                {
                    b.Navigation("Detalle");
                });

            modelBuilder.Entity("SisAlq.Api.Shared.Models.RingresoConsumoCab", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
